"""
SprintGuard PoC - Main Flask Application
Provides REST API for risk assessment, health checks, and scope simulation.
"""
import sys
from flask import Flask, request, jsonify
from flask_cors import CORS

from config import DEBUG, HOST, PORT
from src.data_loader import CSVDataLoader
from src.analyzers import (
    HealthChecker,
    MLRiskAssessor,
    ScopeSimulator
)
from src.utils import format_success, format_error

# Initialize Flask app
app = Flask(__name__)
CORS(app)  # Enable CORS for API access

# Initialize data loader for augmented NeoDataset
print("="*70)
print("SprintGuard - Loading Data...")
print("="*70)

try:
    # Load augmented NeoDataset (generated by scripts/augment_neodataset.py)
    data_loader = CSVDataLoader(high_conf_only=False)
    historical_stories = data_loader.get_all_stories()
    print(f"✓ Loaded {len(historical_stories)} stories from augmented NeoDataset")
except FileNotFoundError as e:
    print(str(e))
    sys.exit(1)
except Exception as e:
    print(f"ERROR: Failed to load data: {str(e)}")
    sys.exit(1)

# Initialize ML Risk Assessor (DistilBERT-XGBoost)
# The model will be loaded automatically from models/ directory
# To train the model:
#   1. Run: python scripts/augment_neodataset.py
#   2. Run: python src/ml/train_risk_model.py
risk_assessor = MLRiskAssessor(
    historical_stories=historical_stories,
    model_dir='models'
)
scope_simulator = ScopeSimulator()


# ============================================================================
# ROUTES
# ============================================================================

@app.route('/api/health-check', methods=['GET'])
def health_check():
    """
    Endpoint: Data Health Check
    
    Analyzes the quality and quantity of historical data.
    Returns scores and recommendations for data improvement.
    """
    import time
    from datetime import datetime
    
    request_start = time.time()
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    print(f"\n[API] {timestamp} - GET /api/health-check")
    print(f"  Remote: {request.remote_addr}")
    
    try:
        # Get all historical stories
        stories = data_loader.get_all_stories()
        print(f"  Analyzing {len(stories)} stories...")
        
        # Perform health check
        checker = HealthChecker(stories)
        result = checker.assess()
        
        request_time = (time.time() - request_start) * 1000
        print(f"  ✓ Health score: {result.health_score:.1f}")
        print(f"  ✓ Time: {request_time:.1f}ms")
        
        return jsonify(format_success(result.to_dict()))
    
    except Exception as e:
        request_time = (time.time() - request_start) * 1000
        print(f"  ✗ ERROR: {str(e)}")
        print(f"  Time: {request_time:.1f}ms")
        return jsonify(format_error(f"Health check failed: {str(e)}", 500))


@app.route('/api/assess-risk', methods=['POST'])
def assess_risk():
    """
    Endpoint: Probabilistic Story Assessor
    
    Request Body:
        {
            "description": "User story description text"
        }
    
    Response:
        {
            "success": true,
            "data": {
                "risk_level": "High|Medium|Low",
                "confidence": 85.0,
                "explanation": "Detailed explanation...",
                "similar_stories": [1, 5, 12]
            }
        }
    """
    import time
    from datetime import datetime
    
    request_start = time.time()
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    print(f"\n[API] {timestamp} - POST /api/assess-risk")
    print(f"  Remote: {request.remote_addr}")
    
    try:
        # Validate request
        data = request.get_json()
        
        if not data or 'description' not in data:
            print(f"  ✗ Validation error: Missing 'description' field")
            return jsonify(format_error("Missing 'description' field in request body"))
        
        description = data['description'].strip()
        
        if not description:
            print(f"  ✗ Validation error: Empty description")
            return jsonify(format_error("Description cannot be empty"))
        
        if len(description) < 3:
            print(f"  ✗ Validation error: Description too short ({len(description)} chars)")
            return jsonify(format_error("Description is too short (minimum 3 characters)"))
        
        print(f"  Request: '{description[:50]}{'...' if len(description) > 50 else ''}'")
        print(f"  Length: {len(description)} characters")
        
        # Perform risk assessment
        assess_start = time.time()
        result = risk_assessor.assess(description)
        assess_time = (time.time() - assess_start) * 1000
        
        request_time = (time.time() - request_start) * 1000
        
        print(f"  ✓ Assessment: {result.risk_level} ({result.confidence:.1f}%)")
        print(f"  ✓ Time: {request_time:.1f}ms (assessment: {assess_time:.1f}ms)")
        
        return jsonify(format_success(result.to_dict()))
    
    except Exception as e:
        request_time = (time.time() - request_start) * 1000
        print(f"  ✗ ERROR: {str(e)}")
        print(f"  Time: {request_time:.1f}ms")
        return jsonify(format_error(f"Risk assessment failed: {str(e)}", 500))


@app.route('/api/simulate-scope', methods=['POST'])
def simulate_scope():
    """
    Endpoint: Scope Impact Simulator
    
    Request Body:
        {
            "current_end_date": "2025-12-15",
            "current_story_points": 20,
            "new_story_points": 5,
            "team_velocity": 2.5  // Optional, defaults to 2.0
        }
    
    Response:
        {
            "success": true,
            "data": {
                "original_end_date": "2025-12-15",
                "new_end_date": "2025-12-17",
                "days_added": 2,
                "impact_summary": "...",
                "recommendations": [...]
            }
        }
    """
    import time
    from datetime import datetime
    
    request_start = time.time()
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    print(f"\n[API] {timestamp} - POST /api/simulate-scope")
    print(f"  Remote: {request.remote_addr}")
    
    try:
        # Validate request
        data = request.get_json()
        
        if not data:
            print(f"  ✗ Validation error: Missing request body")
            return jsonify(format_error("Request body is required"))
        
        # Required fields
        required_fields = ['current_end_date', 'current_story_points', 'new_story_points']
        missing_fields = [f for f in required_fields if f not in data]
        
        if missing_fields:
            print(f"  ✗ Validation error: Missing fields {missing_fields}")
            return jsonify(format_error(
                f"Missing required fields: {', '.join(missing_fields)}"
            ))
        
        # Validate data types and values
        try:
            current_points = int(data['current_story_points'])
            new_points = int(data['new_story_points'])
        except ValueError:
            print(f"  ✗ Validation error: Invalid story points")
            return jsonify(format_error("Story points must be integers"))
        
        if current_points < 0 or new_points < 1:
            print(f"  ✗ Validation error: Invalid point values")
            return jsonify(format_error(
                "Current points must be >= 0 and new points must be >= 1"
            ))
        
        # Optional velocity parameter
        velocity = data.get('team_velocity', 2.0)
        try:
            velocity = float(velocity)
        except ValueError:
            print(f"  ✗ Validation error: Invalid velocity")
            return jsonify(format_error("Team velocity must be a number"))
        
        if velocity <= 0:
            print(f"  ✗ Validation error: Velocity must be positive")
            return jsonify(format_error("Team velocity must be greater than 0"))
        
        print(f"  Request: current={current_points}SP, new={new_points}SP, velocity={velocity}")
        
        # Perform simulation
        result = scope_simulator.simulate_scope_addition(
            current_end_date=data['current_end_date'],
            current_story_points=current_points,
            new_story_points=new_points,
            team_velocity=velocity
        )
        
        request_time = (time.time() - request_start) * 1000
        print(f"  ✓ Simulation: {result.days_added} days added")
        print(f"  ✓ Time: {request_time:.1f}ms")
        
        return jsonify(format_success(result.to_dict()))
    
    except ValueError as e:
        request_time = (time.time() - request_start) * 1000
        print(f"  ✗ ERROR: Invalid date format - {str(e)}")
        print(f"  Time: {request_time:.1f}ms")
        return jsonify(format_error(f"Invalid date format: {str(e)}"))
    except Exception as e:
        request_time = (time.time() - request_start) * 1000
        print(f"  ✗ ERROR: {str(e)}")
        print(f"  Time: {request_time:.1f}ms")
        return jsonify(format_error(f"Simulation failed: {str(e)}", 500))


@app.route('/api/stories', methods=['GET'])
def get_stories():
    """
    Endpoint: Get historical stories (for debugging/exploration)
    
    Query Parameters:
        - risk_level: Filter by risk level (Low/Medium/High)
        - limit: Maximum number of stories to return
    """
    try:
        risk_level = request.args.get('risk_level')
        limit = request.args.get('limit', type=int)
        
        if risk_level:
            stories = data_loader.get_stories_by_risk_level(risk_level)
        else:
            stories = data_loader.get_all_stories()
        
        if limit:
            stories = stories[:limit]
        
        stories_dict = [story.to_dict() for story in stories]
        
        return jsonify(format_success({
            'stories': stories_dict,
            'count': len(stories_dict)
        }))
    
    except Exception as e:
        return jsonify(format_error(f"Failed to fetch stories: {str(e)}", 500))


@app.route('/api/info', methods=['GET'])
def get_info():
    """
    Endpoint: System information
    
    Returns information about the current risk assessor implementation.
    """
    try:
        story_count = data_loader.get_story_count()
        
        info = {
            'risk_assessor': risk_assessor.get_name(),
            'historical_story_count': story_count,
            'version': '1.0.0-PoC'
        }
        
        return jsonify(format_success(info))
    
    except Exception as e:
        return jsonify(format_error(f"Failed to get info: {str(e)}", 500))


# ============================================================================
# ERROR HANDLERS
# ============================================================================

@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors"""
    return jsonify(format_error("Resource not found", 404))


@app.errorhandler(500)
def internal_error(error):
    """Handle 500 errors"""
    return jsonify(format_error("Internal server error", 500))


# ============================================================================
# MAIN
# ============================================================================

if __name__ == '__main__':
    print("=" * 60)
    print("SprintGuard PoC Starting...")
    print("=" * 60)
    print(f"Risk Assessor: {risk_assessor.get_name()}")
    print(f"Historical Stories: {len(historical_stories)}")
    print(f"Server: http://{HOST}:{PORT}")
    print("=" * 60)
    
    app.run(debug=DEBUG, host=HOST, port=PORT)

